# Generated by Django 3.2.5 on 2022-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
